apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-configuration-deployment
  labels:
    app: aurora
spec:
  selector:
    matchLabels:
      app: aurora
  replicas: 1
  template:
    metadata:
      labels:
        app: aurora
    spec:
      containers:
        - name: configuration
          image: marianemuniz/aurora-configuration:latest
          ports:
            - containerPort: 8084
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-configuration-service
spec:
  selector:
    app: configuration
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 31000
  type: NodePort
---