apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: aurora-microservice-deployment
  labels:
    app: aurora
spec:
  selector:
    matchLabels:
      app: aurora
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: aurora
    spec:
      containers:
        - name: configuration
          image: marianemuniz/aurora-configuration:latest
          ports:
            - containerPort: 8084
        - name: discovery
          image: marianemuniz/aurora-discovery:latest
          ports:
            - containerPort: 8081
        - name: auth
          image: marianemuniz/aurora-auth:latest
          ports:
            - containerPort: 8083
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-configuration-service
spec:
  selector:
    app: configuration
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 31000
  type: NodePort
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-discovery-service
spec:
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31001
  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: aurora-auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31002
  type: NodePort