--- # Aurora
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-microservice-deployment
  labels:
    app: aurora
spec:
  selector:
    matchLabels:
      app: aurora
  replicas: 1
  template:
    metadata:
      labels:
        app: aurora
    spec:
      containers:
        - name: configuration
          image: marianemuniz/aurora-configuration:latest
          ports:
            - containerPort: 8084
        - name: discovery
          image: marianemuniz/aurora-discovery:latest
          ports:
            - containerPort: 8081
        - name: auth
          image: marianemuniz/aurora-auth:latest
          ports:
            - containerPort: 8083
        - name: gateway
          image: marianemuniz/aurora-gateway:latest
          ports:
            - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-configuration-service
spec:
  selector:
    app: configuration
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 31000
  type: NodePort
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-discovery-service
spec:
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31001
  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: aurora-auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31002
  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: aurora-gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003
  type: NodePort




--- # Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-microservice-deployment
  labels:
    app: storage
spec:
  selector:
    matchLabels:
      app: storage
  replicas: 1
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: aurora
          image: marianemuniz/storage-aurora:latest
          ports:
            - containerPort: 8082
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: storage-aurora-service
spec:
  selector:
    app: aurora
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31004
  type: NodePort