apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-microservice-deployment
  namespace: aurora
  labels:
    app: aurora
spec:
  selector:
    matchLabels:
      app: aurora
  replicas: 1
  template:
    metadata:
      labels:
        app: aurora
    spec:
      containers:
        - name: auth
          image: marianemuniz/aurora-auth:latest
          ports:
            - containerPort: 8083
        - name: gateway
          image: marianemuniz/aurora-gateway:latest
          ports:
            - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: aurora-auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31002
  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: aurora-gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003
  type: NodePort

---
