--- # Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-microservice-deployment
  labels:
    app: storage
spec:
  selector:
    matchLabels:
      app: storage
  replicas: 1
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: aurora
          image: marianemuniz/storage-aurora:latest
          ports:
            - containerPort: 8082
      hostNetwork: true
      dnsPolicy: Default
---

kind: Service
apiVersion: v1
metadata:
  name: storage-aurora-service
spec:
  selector:
    app: aurora
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31004
  type: NodePort